LMU-147/almost done
AIESEC-Medina/medina-up pull request #47
Opened 2020-10-17 12:48 UTC by Aminebouafia

2020-10-17 13:54 UTC, Nabil-MEDIOUNI commented on src/components/Dashboard/BetaContainer.js
> +            <UserAvatar size="49px" src={getFile(data.cover_photo)} />
data is missing currentPerson: data.currentPerson.cover_photo

2020-10-17 13:55 UTC, Nabil-MEDIOUNI commented on src/components/Dashboard/BetaContainer.js
> +          >
add alignItems="center" to center the name and the avatar))

2020-10-17 13:56 UTC, Nabil-MEDIOUNI commented on src/components/Dashboard/BetaContainer.js
> +        <Box className={classes.boxtheny}>
please avoid "ederja" in writing code))

2020-10-17 13:56 UTC, Nabil-MEDIOUNI commented on src/components/Dashboard/BetaContainer.js
> +          <Box className={classes.boxlywestou}>
same here

2020-10-17 14:01 UTC, Nabil-MEDIOUNI requested changes
please comment the quick links below, we won't need them.
increase the font-size of the quick links and decrease the size of images.
add some margin-top  for the first box and fix the positioning of the word quick links and size.

2020-10-17 14:05 UTC, Nabil-MEDIOUNI commented on src/components/Dashboard/BetaContainer.js
> +      <Box className={classes.boxkbir} mt="20px">
add a <Box /> here for gray bg
<Box position="fixed" bgcolor="#F2F3F6" width="100%" height="100vh" zIndex={-1} />

2020-10-18 02:16 UTC, amalwsl commented
good job <3

2020-10-18 02:16 UTC, merged